version: "3.8"
services:
  crawler:
    image: crawl_telegram_messages:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./telegram.session:/app/telegram.session
    # ports:
    #   - "8000:8000"
    labels:
      - "traefik.enable=true"
      # Router cho HTTPS trên entrypoint websecure
      - "traefik.http.routers.crawler.rule=Host(`telegram.seedlabs.digital`)"
      - "traefik.http.routers.crawler.entrypoints=websecure"
      - "traefik.http.routers.crawler.tls=true"
      - "traefik.http.routers.crawler.tls.certresolver=mytlschallenge"
      # Port bên trong container mà Traefik sẽ forward
      - "traefik.http.services.crawler.loadbalancer.server.port=8000"